#!/bin/bash
# ================================================================
# Codex 项目初始化脚本
#
# 首次使用或克隆项目后手动运行一次：
#   bash .codex/sandbox-setup.sh
#
# 功能：
# - 安装 Git pre-commit hook（commit 时自动触发 Harness 检查）
# - 配置 [notify] hook 指引（Agent turn 完成后自动验证）
# - 验证项目结构完整性
# ================================================================

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

echo "[SETUP] aiGroup Codex Sandbox Initialization"

# 1. Install pre-commit hook (Computational Sensor gate)
if [ -d ".git" ]; then
    echo "[SETUP] Installing pre-commit hook..."
    bash .harness/hooks/install.sh 2>/dev/null || echo "[SETUP] Hook install skipped (not a git repo root)"
fi

# 2. Validate harness integrity
echo "[SETUP] Validating harness integrity..."
bash .harness/structural-tests/test-skill-integrity.sh 2>/dev/null || echo "[SETUP] Skill integrity check failed — review .dev-agents/shared/skills/"
bash .harness/structural-tests/test-persona-refs.sh 2>/dev/null || echo "[SETUP] Persona refs check failed — review .dev-agents/*/PERSONA.md"

# 3. Verify key files exist
echo "[SETUP] Verifying project structure..."
REQUIRED_FILES=(
    "AGENTS.md"
    "ARCHITECTURE.md"
    ".dev-agents/shared/skills/workflow-lifecycle.md"
    ".dev-agents/shared/skills/tdd.md"
    ".dev-agents/shared/skills/verification.md"
    ".harness/run-all.sh"
)

MISSING=0
for f in "${REQUIRED_FILES[@]}"; do
    if [ ! -f "$f" ]; then
        echo "[SETUP] MISSING: $f"
        MISSING=$((MISSING + 1))
    fi
done

if [ $MISSING -gt 0 ]; then
    echo "[SETUP] WARNING: $MISSING required file(s) missing"
else
    echo "[SETUP] All required files present"
fi

# 4. Configure [notify] hook in config.toml
CODEX_CONFIG="$HOME/.codex/config.toml"
NOTIFY_CMD="$PROJECT_ROOT/.codex/hooks/post-turn.sh"

if [ -f "$CODEX_CONFIG" ]; then
    if grep -q "\[notify\]" "$CODEX_CONFIG" 2>/dev/null; then
        echo "[SETUP] [notify] section already exists in $CODEX_CONFIG"
        echo "[SETUP] Verify it points to: $NOTIFY_CMD"
    else
        echo "" >> "$CODEX_CONFIG"
        echo "[notify]" >> "$CODEX_CONFIG"
        echo "command = \"$NOTIFY_CMD\"" >> "$CODEX_CONFIG"
        echo "[SETUP] Added [notify] hook to $CODEX_CONFIG"
    fi
else
    mkdir -p "$(dirname "$CODEX_CONFIG")"
    cat > "$CODEX_CONFIG" << TOML
# aiGroup Codex Configuration (auto-generated by sandbox-setup.sh)

[notify]
command = "$NOTIFY_CMD"
TOML
    echo "[SETUP] Created $CODEX_CONFIG with [notify] hook"
fi

echo "[SETUP] Post-turn Harness checks will run automatically after every Agent turn."

echo ""
echo "[SETUP] Project ready. Agent = Model + Harness."
